server:
  port: 8081
  servlet:
    context-path: /product-service

app:
  api-gateway-url: http://localhost:8000/api/product-service

spring:
  application:
    name: product-service
  profiles:
    active: @spring.profiles.active@
  elasticsearch:
    uris: ${ELASTICSEARCH_HOSTS:http://localhost:9200}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

logging:
  level:
    root: info
    com.iuh: debug
  file:
    name: logs/product-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n" 